export const categoryOptions = [
  { value: '', label: ' - ' },
  { value: 'business', label: 'business' },
  { value: 'entertainment', label: 'entertainment' },
  { value: 'general', label: 'general' },
  { value: 'health', label: 'health' },
  { value: 'science', label: 'science' },
  { value: 'sports', label: 'sports' },
  { value: 'technology', label: 'technology' },
];

export const languageOptions = [
  { value: 'en', label: 'en' },
  { value: 'ru', label: 'ru' },
  { value: 'ar', label: 'ar' },
  { value: 'de', label: 'de' },
  { value: 'es', label: 'es' },
  { value: 'fr', label: 'fr' },
  { value: 'he', label: 'he' },
  { value: 'it', label: 'it' },
  { value: 'nl', label: 'nl' },
  { value: 'no', label: 'no' },
  { value: 'pt', label: 'pt' },
  { value: 'se', label: 'se' },
  { value: 'ud', label: 'ud' },
  { value: 'zh', label: 'zh' },
];

export const countryOptions = [
  { value: '', label: ' - ' },
  { value: 'ae', label: 'ae' },
  { value: 'ar', label: 'ar' },
  { value: 'at', label: 'at' },
  { value: 'au', label: 'au' },
  { value: 'be', label: 'be' },
  { value: 'bg', label: 'bg' },
  { value: 'br', label: 'br' },
  { value: 'ca', label: 'ca' },
  { value: 'ch', label: 'ch' },
  { value: 'cn', label: 'cn' },
  { value: 'co', label: 'co' },
  { value: 'cu', label: 'cu' },
  { value: 'cz', label: 'cz' },
  { value: 'de', label: 'de' },
  { value: 'eg', label: 'eg' },
  { value: 'fr', label: 'fr' },
  { value: 'gb', label: 'gb' },
  { value: 'gr', label: 'gr' },
  { value: 'hk', label: 'hk' },
  { value: 'hu', label: 'hu' },
  { value: 'id', label: 'id' },
  { value: 'ie', label: 'ie' },
  { value: 'il', label: 'il' },
  { value: 'in', label: 'in' },
  { value: 'it', label: 'it' },
  { value: 'jp', label: 'jp' },
  { value: 'kr', label: 'kr' },
  { value: 'lt', label: 'lt' },
  { value: 'lv', label: 'lv' },
  { value: 'ma', label: 'ma' },
  { value: 'mx', label: 'mx' },
  { value: 'my', label: 'my' },
  { value: 'ng', label: 'ng' },
  { value: 'nl', label: 'nl' },
  { value: 'no', label: 'no' },
  { value: 'nz', label: 'nz' },
  { value: 'ph', label: 'ph' },
  { value: 'pl', label: 'pl' },
  { value: 'pt', label: 'pt' },
  { value: 'ro', label: 'ro' },
  { value: 'rs', label: 'rs' },
  { value: 'ru', label: 'ru' },
  { value: 'sa', label: 'sa' },
  { value: 'se', label: 'se' },
  { value: 'sg', label: 'sg' },
  { value: 'si', label: 'si' },
  { value: 'sk', label: 'sk' },
  { value: 'th', label: 'th' },
  { value: 'tr', label: 'tr' },
  { value: 'tw', label: 'tw' },
  { value: 'ua', label: 'ua' },
  { value: 'us', label: 'us' },
  { value: 've', label: 've' },
  { value: 'za', label: 'za' },
];
